name: ci

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0

  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Test
        run: |
          make test

  trigger-deployment:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [lint, unit]
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          script: |
            github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.sha }}',
              environment: 'staging',
              auto_merge: false,
              required_contexts: [],
            })
